feat: mobile responsive design
PoliNetworkOrg/TheTOLProject pull request #11
Opened 2022-04-12 18:39 UTC by toto04

I've implemented a responsive mobile design using a context that gets updated when the window is resized, toggling the mobile styles in the components if the width is less than 768px (I blame copilot for the random number, idk).

I tried to leave the desktop design as untouched as possible, I just added some wrapper divs around a couple of components, and slightly modifying some css behavior for smaller screens (like addend a display flex in the answer radio buttons to prevent weird positioning). Also slightly modified the behavior of the Recap Bar, for a better usability and readability on phones (a scroll is automatically with a useEffect in the [QuestionForm](src/components/QuestionForm/QuestionForm.tsx) applied to keep the selected cell in view)

2022-04-13 21:52 UTC, EndBug requested changes
Awesome work man ✌🏻 
Everything seems to work well, I just have a couple of minor comments. Let me know what you think!

2022-04-13 21:52 UTC, EndBug commented on src/components/InfoView/InfoEnd.tsx
> +  },
In the desktop version the results table is now aligned to the left. Is this a conscious decision or just an oversight?

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/26386270/163275542-6e0e7b81-a2dd-4ffe-9d88-441b1cbbbc53.png">

2022-04-13 21:52 UTC, EndBug commented on src/components/QuestionsForm/TopControls.tsx
> +
Even though the timer is not a button, it could use a bit more room below, to separate it from the recap bar

<img width="284" alt="image" src="https://user-images.githubusercontent.com/26386270/163275156-9bcd50b7-e18a-468f-85a8-6bd875680593.png">

2022-04-13 21:52 UTC, EndBug commented on src/components/QuestionsForm/Timer.tsx
> +      >
I've noticed that the timer description ends up a bit distant from the actual timer in the mobile version: I think that we can maybe hide it (with styles), the timer symbol is pretty self-explanatory anyway.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/26386270/163274212-33bcbad3-a992-459d-9bfb-99f869d5c4bc.png">

2022-04-14 08:59 UTC, toto04 commented on src/components/InfoView/InfoEnd.tsx
> +  },
nope, def an oversight oops 😬

2022-04-14 09:04 UTC, toto04 commented on src/components/QuestionsForm/Timer.tsx
> +      >
yeah that's what I thought as well, but I didn't want to remove / modify any UI element, I tried just moving them around

I personally feel like the timer description is pretty much useless on desktop too, do you want to remove it from both mobile and desktop or just mobile? I don't know if it's there for consistency with the real TOL interface, in which case we can simply remove it from the mobile to avoid clutter

2022-04-14 09:34 UTC, EndBug commented on src/components/QuestionsForm/Timer.tsx
> +      >
I think it was added because it's present in the official DOL:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/26386270/163356719-05f1477d-8103-4dc3-8758-3d23cdb7c9b4.png">

I guess it makes sense to have it because a first-time user could otherwise think that the timer is for the whole test, instead of a single section...

I guess that we can just add a bit more padding below and just keep it the way it is

2022-04-16 16:24 UTC, toto04 commented on src/components/QuestionsForm/TopControls.tsx
> +
added the same 1em margin provided above by the p element, now the margin is coherent both above and below the timer

2022-04-16 16:28 UTC, toto04 commented on src/components/QuestionsForm/Timer.tsx
> +      >
I tried removing it to reduce a bit of a crowded feel, if you like it you can go ahead and merge, otherwise if you think it's a bit too empty we can try restoring the text but maybe align it to the right?

2022-04-16 17:21 UTC, EndBug commented on src/components/QuestionsForm/Timer.tsx
> +      >
I don't mind the space, looks good to me 👍🏻

2022-04-16 17:23 UTC, EndBug approved these changes
LGTM ✅ 
We can merge this after we set up the staging website, this way it's not instantly deployed to production

2022-04-16 22:14 UTC, merged