feat: update eslint and add rules
PoliNetworkOrg/TheTOLProject pull request #111
Opened 2024-02-05 21:10 UTC by lorenzocorallo

- update `eslint` packages to latest version
- separate `prettier` from `eslint` (best practice: formatter and linter should be separated for performance)
- add rules to prevent unused imports and variables
- migrate existing code to be aligned with new rules

Note: in `scripts/database.ts` a lot of rules are ignored because it's actually pretty difficult to strictly-type it. In future we should consider rewriting it in a smarter way.

2024-02-13 19:00 UTC, EndBug requested changes

2024-02-13 19:00 UTC, EndBug commented on src/components/pages/QPreview.tsx
>    // eslint-disable-next-line @typescript-eslint/no-explicit-any
```suggestion
```

This is no longer necessary :)

2024-02-13 19:00 UTC, EndBug commented on src/components/Header.tsx
> +    void i18n.changeLanguage(lang) // should we care about this promise?
We probably should (?)
I guess it would make sense to change the language option only after a successful language change, in case it ever breaks mid-change.
I feel like this would require i18n being broken, but who knows! We're probably safer waiting for that promise to resolve before updating the settings
Good catch!

2024-02-13 19:00 UTC, EndBug commented on src/i18n.ts
> +// should we care about this promise?
Probably not, since we're exporting the "builder" and not the promise itself...
I mean, it would make sense to wait for it to be ready, but I think that's already handled by the fact that we're using the `useTranslation` hook from `react-i18next`
The only place we're using this file's export is to pass it to the i18n provider in the index file, so I guess it's fine

@toto04 Just to be sure, are you aware of any shortcomings of this approach?

2024-02-13 21:12 UTC, EndBug commented on src/i18n.ts
> +// should we care about this promise?
damn, nice work!
so, bottom line: I guess we can just keep it this way, as adding anything else would be just for the sake of overengineering it
and if not, feel free to roast me in 10 years when the project breaks because of this decision 😂

2024-02-16 11:23 UTC, lorenzocorallo commented on src/i18n.ts
> +// should we care about this promise?
@toto04 great work! I agree to leave it as it is.

2024-02-16 14:12 UTC, lorenzocorallo commented
note: forced pushed from c6084767b92fbb2d732520dbd0c58a97345c9bf6 to 4b752f4655581664691b2f40d05dbf9f303828cf for wrong commit message

2024-02-19 18:56 UTC, lorenzocorallo commented on package.json
> +    "lint:fix": "eslint ./src ./scripts --fix --ext .ts,.tsx && npm run format && npm run exports",
Probably you are right. Not able to test it right now.

Even if it doesn't fix the problem, shouldn't we show its output in any case? Otherwise the developer may run only the lint:fix and skipping the exports problem

2024-02-20 20:00 UTC, EndBug commented on package.json
> +    "lint:fix": "eslint ./src ./scripts --fix --ext .ts,.tsx && npm run format && npm run exports",
Hmm your point makes sense!
Let's leave this this way: if we see that it bothers somebody, it's a quick fix ;)

2024-02-21 00:11 UTC, lorenzocorallo commented
I think that all the review comments have been addressed, so we can proceed to merge.
@toto04 @toto04 all right?

2024-02-21 09:38 UTC, EndBug commented
@lorenzocorallo I haven't been able to test this locally yet, that's why the review is not approved yet. Sorry :/

2024-02-26 23:10 UTC, EndBug approved these changes
Awesome work @lorenzocorallo, LGTM ✅ 
(and sorry for the long waiting time)

2024-02-26 23:11 UTC, merged