Improve end-of-simulation PDF
PoliNetworkOrg/TheTOLProject pull request #59
Opened 2023-02-06 12:55 UTC by lorenzocorallo

A new component `Question` was created to display questions in the same way in different pages.
It was used in `dbpreview` route and in the `PrintDocument` component (the one used to print the PDF)

The component has the following props:
- `isDebug` to display question id and validation (used for `dbpreview`)
- `isTest` to include test choice and result (that is "Senza Risposta" || "Esatta" || "Errata" in the results PDF)
- `q` which is the question itself to be displayed
- `choice` meant to be used with `isTest = true` to pass through the "letter" of the user guess

Following the layout of `dbpreview` questions:

- an arrow marks the correct answer
- if the user has made a choice, the answer selected is displayed in bold
- letters are displayed (before they weren't)

As a new implementation, feel free to give your opinions besides the bare code review.

p.s.: there was a blank page (position 2) in the results PDF, which has been removed.

2023-02-06 20:19 UTC, EndBug requested changes
Awesome, I just left a comment about the document style

2023-02-06 20:19 UTC, EndBug commented on src/components/Util/Question.tsx
> +              fontWeight: letter === choice ? 'bold' : 'normal'
I think that making this text bold gets a bit confusing with wrong answers: how about making the **correct** answer bold, and ~striking out~ the wrong answer?

<img width="169" alt="image" src="https://user-images.githubusercontent.com/26386270/217075776-73fde1fd-b3c9-4b4f-9da8-caeba8d3c334.png">

2023-02-06 20:53 UTC, lorenzocorallo commented on src/components/Util/Question.tsx
> +              fontWeight: letter === choice ? 'bold' : 'normal'
Striking out could make the answer unreadable, but I can agree that it's not the best styling right now.
The goal of this implementation was to permit the user to publish the question on the telegram group, so striking out the answer can make the visualization worse.
Maybe we can keep the bold for the correct answer and insert next to "Errata"/"Corretta" the letter chosen by user in parenthesis (es. `Errata (scelta: A)`) . 
Another option is to change "Errata" and "Corretta" to "A: Errata", "B: Corretta", so displaying the letter chosen followed by the result.
What do you think about it?

2023-02-06 21:06 UTC, EndBug commented on src/components/Util/Question.tsx
> +              fontWeight: letter === choice ? 'bold' : 'normal'
Hmmm, how about changing the symbol? We can put a tick next to the correct answer, and a cross next to the wrong one. This would replace the arrow

2023-02-06 21:06 UTC, EndBug commented on src/components/Util/Question.tsx
> +              fontWeight: letter === choice ? 'bold' : 'normal'
We could also play a bit with color, but I don't want that to be the only aspect since people may see this in black and white.

2023-02-07 18:59 UTC, EndBug approved these changes
Awesome, I like it!

@toto04 Would you mind giving it a second look?

2023-02-08 21:17 UTC, merged

2023-02-10 21:56 UTC, EndBug commented
@all-contributors please add @lorenzocorallo for their code and bug contributions