Add support for students with DSA, based on official PoliMi rules
PoliNetworkOrg/TheTOLProject pull request #69
Opened 2023-03-14 22:34 UTC by lorenzocorallo

Changes:

- Added a new context `TestContext` which describes states related to the test. At the moment has been implemented the DSA toggle, so that when the user toggle the checkbox, the value is automatically updated in localStorage and it can be used in lower components
- Added new constant `DSATimeModifier = 1.3` which is used to multiply minutes available for every section when DSA toggle is active
-

2023-03-15 18:42 UTC, EndBug requested changes
As always, awesome work!
Just a couple of comments below ;)

2023-03-15 18:42 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +          E' inoltre richiesta una certificazione attestante la diagnosi di DSA.{' '}
```suggestion
          È inoltre richiesta una certificazione attestante la diagnosi di DSA.{' '}
```

🙃

2023-03-15 18:42 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +      <div style={{ ...styles.dsaInfo, display: isDsa ? 'block' : 'none' }}>
Did you try using the `Collapsible` component? Was it bad looking?

2023-03-15 18:42 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +    maxWidth: 600
I see you're limiting the width of the text to improving readability.
While we're at it, how would you feel about further limiting the homepage text too? I think it's way too large ahahhah, maybe we can do something coherent

2023-03-15 20:15 UTC, lorenzocorallo commented on src/components/InfoView/InfoStart.tsx
> +    maxWidth: 600
Ok I see. I thought the homepage text was done like that because the idea was to make the website "ugly" as the real test ahahah

2023-03-15 20:19 UTC, lorenzocorallo commented on src/components/InfoView/InfoStart.tsx
> +      <div style={{ ...styles.dsaInfo, display: isDsa ? 'block' : 'none' }}>
I don't know if Collapsible fit in this use case. The idea is that that text is always visible when the checkbox is on and is always hidden when it is off, so setting the display css prop is appropriate.
Why would you recommend use that component?

2023-03-15 20:24 UTC, lorenzocorallo commented on src/components/InfoView/InfoStart.tsx
> +          E' inoltre richiesta una certificazione attestante la diagnosi di DSA.{' '}
Does the accented letter give any problem with HTML or is there any other reason for not using it? Just to know, gonna change it anyway 🫣🙃

2023-03-15 20:27 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +    maxWidth: 600
This time it's our fault ahhahaha

2023-03-15 20:27 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +          E' inoltre richiesta una certificazione attestante la diagnosi di DSA.{' '}
No, afaik 🤷🏻

2023-03-15 20:28 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +      <div style={{ ...styles.dsaInfo, display: isDsa ? 'block' : 'none' }}>
Just because it has a nicer animation ahahha
We could bound the open state of the collapsible to the checkbox, hiding the button, if we wanted to

2023-03-15 20:31 UTC, lorenzocorallo commented on src/components/InfoView/InfoStart.tsx
> +      <div style={{ ...styles.dsaInfo, display: isDsa ? 'block' : 'none' }}>
Ok, I will try it

2023-03-17 16:09 UTC, EndBug reviewed
Nice! LGTM ✅ 
I'm just waiting for a question of mine to be answered regarding a privacy thing, after that it'll be good to merge 👍🏻

2023-03-24 23:15 UTC, EndBug requested changes
Ok, so, here's what we need to do:

- [ ] Add a paragraph about how we use the local storage in the website's privacy policy
- [ ] Mention that the local storage is never sent to any server
- [ ] Preferences older than 6 months should be deleted

If you need any help with this just let me know, and I'll take it from here
Thanks again for the help 💖

2023-03-27 16:52 UTC, EndBug reviewed
Awesome ✅ 
Just left a comment regarding the GitHub logo, I'll wait for Tommaso's take on that 👍🏻

2023-03-27 16:52 UTC, EndBug commented on src/components/Footer.tsx
> +        <img src={githubLogo} style={styles.githubLogo}></img>
I'm not sure about this, it might be "too good" compared to the rest of the website...
@toto04 what's your take on this?

2023-03-27 16:52 UTC, EndBug commented on src/components/InfoView/InfoStart.tsx
> +      </Collapsible>
Looks good! Just for future reference: since this is extra info targeted to actual test takers, I don't think it needs to be translated to English.

It still makes sense to keep English paragraphs for info about the website, and now about the test itself.

2023-03-30 05:56 UTC, toto04 commented on src/components/Footer.tsx
> +        <img src={githubLogo} style={styles.githubLogo}></img>
meh, it really does stand out a bit, I could see this being here if all other options in the footer had an icon as well, but as it is I think it draws a bit too much attention where it really shouldn't
Imho this should get removed, but it's not a big deal by any means ahah

2023-03-30 12:41 UTC, toto04 commented on src/components/Footer.tsx
> +        <img src={githubLogo} style={styles.githubLogo}></img>
> It was just an idea to inform the user that it is an external link and not an internal one.
that's a great point actually, I, personally, wouldn't know how to convey this without making it stand out this much, @EndBug it should be your call to make, in the end that's a detail, it doesn't really matter if we keep it or delete it

2023-03-31 11:44 UTC, EndBug commented on src/components/Footer.tsx
> +        <img src={githubLogo} style={styles.githubLogo}></img>
Honestly, I'd rather remove this: it's true that it's an external link, but we're also opening it in a new tab by default
I'll do this right away so that we can merge this PR ✅

2023-04-01 20:37 UTC, EndBug approved these changes

2023-04-01 20:37 UTC, merged